
import bb.classes.connection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cs
 */
public class EmployeeList extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeList
     */
    public EmployeeList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblemplist = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EmployeeListForm");
        setBackground(java.awt.Color.cyan);
        setForeground(java.awt.Color.cyan);

        tblemplist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee_ID", "First_Name", "Last_Name", "Sex", "Address", "Phone_Number"
            }
        ));
        jScrollPane1.setViewportView(tblemplist);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnNew)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(btnRefresh)
                .addGap(29, 29, 29)
                .addComponent(btnCancel)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnNew)
                    .addComponent(jButton1)
                    .addComponent(btnRefresh)
                    .addComponent(btnCancel))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        deleteFaculty();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        insertFaculty();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateFaculty();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        readFaculty();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblemplist;
    // End of variables declaration//GEN-END:variables


 Connection conn = null;
        Statement stmt = null;
        ResultSet rst = null;
    
    
    
    private void readFaculty() {
       
        DefaultTableModel facultyTblModel = (DefaultTableModel) tblemplist.getModel();
        facultyTblModel.setRowCount(0);
        String sql = "Select * From Employee order by First_Name ASC";
        try {
            conn = connection.getConn();
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rst = stmt.executeQuery(sql);
            int row = 0;
            while (rst.next()) {
                facultyTblModel.addRow(new Object[]{rst.getString("Employee_ID"),rst.getString("First_Name"), rst.getString("Last_Name"), rst.getString("Sex"), rst.getString("Address"), rst.getString("Phone_Number")});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        } finally {
        }

    }
    //******************Table Action Column****************************//
    private void setTableActionColumn(){
        TableColumn tbcAction = tblemplist.getColumnModel().getColumn(5);
            JCheckBox cmbDelete = new JCheckBox();
            tbcAction.setCellEditor(new DefaultCellEditor(cmbDelete));
    }

private void insertFaculty() {
        DefaultTableModel facultyTblModel = (DefaultTableModel) tblemplist.getModel();
        if (btnNew.getText().equalsIgnoreCase("New")) {
            int emptrow = facultyTblModel.getRowCount() + 1;
            facultyTblModel.setRowCount(emptrow);
            btnNew.setText("Save");
        } else {
            int newrow = facultyTblModel.getRowCount()-1;
            try {
                rst.moveToInsertRow();
                rst.updateString("Employee_ID", facultyTblModel.getValueAt(newrow, 1).toString());
                rst.updateString("First_Name", facultyTblModel.getValueAt(newrow, 2).toString());
                rst.updateString("Last_Name", facultyTblModel.getValueAt(newrow, 3).toString());
                rst.updateString("Sex", facultyTblModel.getValueAt(newrow, 4).toString());
                rst.updateString("Address", facultyTblModel.getValueAt(newrow, 5).toString());
                rst.updateString("Phone_Number", facultyTblModel.getValueAt(newrow, 5).toString());
                rst.insertRow();
                rst.moveToCurrentRow();
                JOptionPane.showMessageDialog(this, "Record saved successfully.");
                btnNew.setText("New");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
            }
        }
    }
private void updateFaculty() {
        DefaultTableModel facultyTblModel = (DefaultTableModel) tblemplist.getModel();
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to update the selected record?");
            if (resp == JOptionPane.YES_OPTION) {
                int row = tblemplist.getSelectedRow() + 1;
                rst.absolute(row);
                rst.updateString("Employee_ID", facultyTblModel.getValueAt(tblemplist.getSelectedRow(), 1).toString());
                rst.updateString("First_Name", facultyTblModel.getValueAt(tblemplist.getSelectedRow(), 2).toString());
                rst.updateString("Last_Name", facultyTblModel.getValueAt(tblemplist.getSelectedRow(), 3).toString());
                rst.updateString("Sex", facultyTblModel.getValueAt(tblemplist.getSelectedRow(), 4).toString());
                rst.updateString("Addressr", facultyTblModel.getValueAt(tblemplist.getSelectedRow(), 5).toString());
                 rst.updateString("Phone_Number", facultyTblModel.getValueAt(tblemplist.getSelectedRow(), 5).toString());
                rst.updateRow();
                JOptionPane.showMessageDialog(this, "Record updated successfully.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }private void deleteFaculty() {
        try {
            int resp = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected record?");
            if (resp == JOptionPane.YES_OPTION) {
                int row = tblemplist.getSelectedRow() + 1;
                rst.absolute(row);
                rst.deleteRow();
                JOptionPane.showMessageDialog(this, "Record deleted successfully.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database server error" + e.getMessage());
        }
    }


}
